name: sprint5
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.3.0
  path_provider: ^2.1.4
  audioplayers: ^0.20.1
  dart_openai: ^1.0.0  # Replace with the latest version available
  flutter_dotenv: ^5.0.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  http: ^0.13.6
  provider: ^6.0.0 
  envied: ^0.5.4+1
  envied_generator: ^0.5.4+1
  confetti: ^0.6.0
  fl_chart: ^0.69.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7 # Check for the latest version on pub.dev


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/video1.mp4
    - assets/win.mp3
    - assets/lose.mp3
    - assets/info-1.png
    - assets/info-2.png
    - assets/image.png
    - assets/background.png
    - assets/momentvm-logo-big.png
    - assets/home.png
    - assets/profile.png
    - assets/locked.png
    - assets/start.png
    - assets/iconText.png
    - assets/iconHeadphones.png
    - assets/courses.json
    - assets/checked.png
    - assets/ring.png
    - assets/fire.png
    - assets/heart.png
    - assets/xp.png
    - assets/star-filled.png
    - assets/star.png
    - assets/onboarding-3.png
    - assets/arrow.png
    - assets/loved.png
    - assets/unsatisfied.png
    - assets/ok.png
    - assets/ex.png
    - assets/horray.png
    - assets/character.png
    - assets/interests.json
    - assets/budget_basics.png
    - assets/nil/
    - assets/nil-vids/video-1.mp4
    - assets/nil-vids/video-2.mp4
    - assets/nil-vids/video-3.mp4
    - assets/nil-vids/video-4.mp4
    - assets/nil-vids/video-5.mp4
    - assets/nil-vids/video-6.mp4
    - assets/nil-vids/video-7.mp4
    - assets/nil-vids/video-8.mp4
    - assets/nil-vids/video-9.mp4












  fonts:
  - family: Lexend-Bold
    fonts:
      - asset: assets/fonts/Lexend-Bold.ttf
        weight: 700

  - family: Lexend-Regular
    fonts:
      - asset: assets/fonts/Lexend-Regular.ttf
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
